// src/api/mockServices.js
export const MOCK_SERVICES = [
  {
    id: 1,
    title: "Pintura Residencial",
    description: "Pintura completa de casas e apartamentos, interior e exterior. Experiência de 10 anos.",
    price: "A negociar",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400&q=80",
    icon: "🎨",
    requester: { full_name: "João Silva", email: "jo******@gmail.com" }
  },
  {
    id: 2,
    title: "Bicicleta Usada",
    description: "Bicicleta aro 26 em bom estado, revisada recentemente. Acompanha capacete.",
    price: "R$ 350",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&q=80",
    icon: "🚲",
    requester: { full_name: "Maria Santos", email: "ma******@gmail.com" }
  },
  {
    id: 3,
    title: "Aulas de Violão",
    description: "Aulas para iniciantes e intermediários, 1 hora por semana. Primeiro contato gratuito.",
    price: "R$ 60/hora",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&q=80",
    icon: "🎸",
    requester: { full_name: "Carlos Melo", email: "ca******@gmail.com" }
  },
  {
    id: 4,
    title: "Sofá 3 Lugares",
    description: "Sofá retrátil e reclinável, tecido cinza, pouquíssimo uso. Retirar no local.",
    price: "R$ 800",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",
    icon: "🛋️",
    requester: { full_name: "Ana Ribeiro", email: "an******@gmail.com" }
  },
  {
    id: 5,
    title: "Encanamento e Hidráulica",
    description: "Reparos em vazamentos, instalação de torneiras, chuveiros e caixas d'água.",
    price: "R$ 80/hora",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&q=80",
    icon: "🔧",
    requester: { full_name: "Pedro Costa", email: "pe******@gmail.com" }
  },
  {
    id: 6,
    title: "Notebook Dell i5",
    description: "Notebook Dell Inspiron i5 8GB RAM, SSD 256GB, tela 15.6. Funcionando perfeitamente.",
    price: "R$ 1.800",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&q=80",
    icon: "💻",
    requester: { full_name: "Lucas Ferreira", email: "lu******@gmail.com" }
  },
  {
    id: 7,
    title: "Jardinagem e Paisagismo",
    description: "Corte de grama, poda de árvores, plantio e manutenção de jardins.",
    price: "A negociar",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80",
    icon: "🌿",
    requester: { full_name: "Roberto Lima", email: "ro******@gmail.com" }
  },
  {
    id: 8,
    title: "Mesa de Jantar 6 Cadeiras",
    description: "Mesa de madeira maciça com 6 cadeiras estofadas. 1,80m x 90cm. Estado impecável.",
    price: "R$ 1.200",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?w=400&q=80",
    icon: "🪑",
    requester: { full_name: "Fernanda Oliveira", email: "fe******@gmail.com" }
  },
  {
    id: 9,
    title: "Manutenção de Ar-condicionado",
    description: "Limpeza completa, recarga de gás e reparos em geral. Atendimento residencial e comercial.",
    price: "R$ 150",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=400&q=80",
    icon: "❄️",
    requester: { full_name: "Marcos Viana", email: "ma******@gmail.com" }
  },
  {
    id: 10,
    title: "Personal Trainer",
    description: "Treinos personalizados para emagrecimento ou hipertrofia. Presencial ou online.",
    price: "R$ 70/aula",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
    icon: "💪",
    requester: { full_name: "Ricardo Alves", email: "ri******@gmail.com" }
  },
  {
    id: 11,
    title: "Monitor 24 Pol Dell",
    description: "Resolução Full HD, entradas HDMI e DisplayPort. Base com ajuste de altura.",
    price: "R$ 600",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80",
    icon: "🖥️",
    requester: { full_name: "Beto Souza", email: "be******@gmail.com" }
  },
  {
    id: 12,
    title: "Limpeza de Estofados",
    description: "Higienização profunda de sofás, poltronas e tapetes. Eliminamos odores e manchas.",
    price: "A partir de R$ 120",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80",
    icon: "🧼",
    requester: { full_name: "Sonia Abrão", email: "so******@gmail.com" }
  },
  {
    id: 13,
    title: "Violão Yamaha C40",
    description: "Violão acústico com cordas de nylon. Ideal para estudantes. Acompanha capa.",
    price: "R$ 550",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1550985616-10810253b84d?w=400&q=80",
    icon: "🎸",
    requester: { full_name: "Tiago Iorc", email: "ti******@gmail.com" }
  },
  {
    id: 14,
    title: "Dog Walker",
    description: "Passeios de 45 minutos para cães de todos os portes. Muita paciência e carinho.",
    price: "R$ 30/passeio",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&q=80",
    icon: "🐕",
    requester: { full_name: "Gabriela Rocha", email: "ga******@gmail.com" }
  },
  {
    id: 15,
    title: "Tradução Inglês/Português",
    description: "Tradução de artigos, sites e documentos técnicos. Fluência nativa.",
    price: "R$ 0,15/palavra",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&q=80",
    icon: "🇺🇸",
    requester: { full_name: "Enzo Gabriel", email: "en******@gmail.com" }
  },
  {
    id: 16,
    title: "Teclado Mecânico RGB",
    description: "Switch Blue, padrão ABNT2. Perfeito para jogos e digitação.",
    price: "R$ 150",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&q=80",
    icon: "⌨️",
    requester: { full_name: "Bruno Gagliasso", email: "br******@gmail.com" }
  },
  {
    id: 17,
    title: "Cadeira de Escritório",
    description: "Modelo giratório com rodinhas, ajuste de altura e encosto confortável.",
    price: "R$ 250",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&q=80",
    icon: "💺",
    requester: { full_name: "Daniel Oliveira", email: "da******@gmail.com" }
  },
  {
    id: 18,
    title: "Instalação Elétrica",
    description: "Troca de fiação, instalação de lustres, tomadas e disjuntores.",
    price: "R$ 90/hora",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&q=80",
    icon: "⚡",
    requester: { full_name: "Jorge Aragão", email: "jo******@gmail.com" }
  },
  {
    id: 19,
    title: "Aulas de Matemática",
    description: "Reforço escolar para Ensino Fundamental e Médio. Preparação para ENEM.",
    price: "R$ 50/hora",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&q=80",
    icon: "📐",
    requester: { full_name: "Silvio Santos", email: "si******@gmail.com" }
  },
  {
    id: 20,
    title: "Skate Completo",
    description: "Shape de maple, trucks resistentes e rodas para asfalto. Pouco uso.",
    price: "R$ 180",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=400&q=80",
    icon: "🛹",
    requester: { full_name: "Rayssa Leal", email: "ra******@gmail.com" }
  },
  {
    id: 21,
    title: "Câmera Canon T7i",
    description: "Corpo + Lente 18-55mm. Acompanha bolsa, cartão 64GB e 2 baterias.",
    price: "R$ 2.800",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
    icon: "📷",
    requester: { full_name: "Sebastião Salgado", email: "se******@gmail.com" }
  },
  {
    id: 22,
    title: "Desenvolvedor Freelance",
    description: "Criação de sites institucionais, landing pages e pequenos sistemas web.",
    price: "A negociar",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&q=80",
    icon: "💻",
    requester: { full_name: "Davi Ribeiro", email: "da******@gmail.com" }
  },
  {
    id: 23,
    title: "Prancha de Surf",
    description: "Modelo Funboard 7'2'', ideal para quem está começando. Com leashes e quilhas.",
    price: "R$ 900",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=400&q=80",
    icon: "🏄",
    requester: { full_name: "Gabriel Medina", email: "ga******@gmail.com" }
  },
  {
    id: 24,
    title: "Chef de Cozinha em Casa",
    description: "Preparo jantares especiais, eventos íntimos ou cardápio semanal saudável.",
    price: "R$ 200/evento",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&q=80",
    icon: "👨‍🍳",
    requester: { full_name: "Alex Atala", email: "al******@gmail.com" }
  },
  {
    id: 25,
    title: "Fone de Ouvido Sony XM4",
    description: "Cancelamento de ruído top de linha. Bateria dura 30 horas. Estado de novo.",
    price: "R$ 1.200",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
    icon: "🎧",
    requester: { full_name: "Alok Petrillo", email: "al******@gmail.com" }
  },
  {
    id: 26,
    title: "Máquina de Café Nespresso",
    description: "Modelo Essenza Mini, compacta e rápida. Brinde: porta cápsulas.",
    price: "R$ 300",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400&q=80",
    icon: "☕",
    requester: { full_name: "Ana Maria Braga", email: "an******@gmail.com" }
  },
  {
    id: 27,
    title: "Barraca de Camping 4 Pessoas",
    description: "Marca Quechua, fácil montagem (2 seconds). Impermeável e espaçosa.",
    price: "R$ 400",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80",
    icon: "⛺",
    requester: { full_name: "Bear Grylls", email: "be******@gmail.com" }
  },
  {
    id: 28,
    title: "Fotografia para Eventos",
    description: "Aniversários, batizados e ensaios externos. Entrega de fotos editadas.",
    price: "R$ 500",
    status: "OPEN",
    category: "SERVICE",
    photo_url: "https://images.unsplash.com/photo-1520857014576-2c4f4c972b57?w=400&q=80",
    icon: "📸",
    requester: { full_name: "Bob Wolfenson", email: "bo******@gmail.com" }
  },
  {
    id: 29,
    title: "Mochila Cargueira 60L",
    description: "Ideal para mochilão ou trilhas longas. Diversos compartimentos e capa de chuva.",
    price: "R$ 350",
    status: "OPEN",
    category: "PRODUCT",
    photo_url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80",
    icon: "🎒",
    requester: { full_name: "Amyr Klink", email: "am******@gmail.com" }
  }
]